server:
  port: 18091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
spring:
  thymeleaf:
    cache: false
  application:
    name: web-backstage
  main:
    allow-bean-definition-overriding: true
  cache: false
  resources:
    static-locations: classpath:/templates/,classpath:/static/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
#超时配置
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 5000

