server:
  port: 18088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
#  resources:
#    static-locations: classpath:/templates/,classpath:/static/
  #rabbitmq:
  #  host: 192.168.25.138
# 生成静态页的位置
pagepath: D:/idea-develop/changgou/changgou-parent/changgou-web/changgou-web-item/src/main/resources/templates/items
ribbon:
  ReadTimeout: 600000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000