server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #eureka 地址
spring:
  application:
    name: eureka
# redis-trib.rb:ruby的脚本对象,用来实现Redis集群创建,脚本对象在redis的解压安装包中
# create:创建集群
# --replicas:添加主从
# 1:集群和主从之间的筛选采取随机策略
# IP:端口   参与集群和主从配置的节点信息
#./redis-trib.rb create --replicas 1 192.168.211.132:7001 192.168.211.132:7002 192.168.211.132:7003 192.168.211.132:7004 192.168.211.132:7005 192.168.211.132:7006