server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.211.132
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/changgou_oauth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      #defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8763/eureka,http://127.0.0.1:8764/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou #客户端ID
  clientSecret: changgou #客户端密钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt: #本地证书和密钥以及证书密码的配置
  key-store:
    location: classpath:/changgou.jks #证书路径
    secret: changgou #密钥
    alias: changgou #证书别名
    password: changgou
    #公钥加密  私钥解密  采用非对称算法->RSA
    #MDS: 摘要加密         AES、DESC: 对称加密